apiVersion: v1
kind: Service
metadata:
  name: abc-technology-service
  namespace: abctechnologies
spec:
  type: NodePort
  selector:
    app: abc-technology
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
